spring:
  datasource:
    url: jdbc:h2:file:./data/profiledb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally-quoted_identifiers: true
    hibernate:
      ddl-auto: update
      show-sql: enabled
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  r2dbc:
    url: r2dbc:h2:file:///./data/profiledb
    username: sa
    password:
  main:
    web-application-type: reactive

